package testify

import (
	"runtime"
	"strings"

	"github.com/get-skipper/skipper-go/core"
)

// testIDFromSuite builds a Skipper test ID for a testify suite test.
//
// t.Name() inside a testify suite method returns "TestSuiteName/TestMethodName".
// We split on "/" and combine with the file path captured at SetupSuite time.
func testIDFromSuite(name, file string) string {
	parts := splitSuiteName(name)
	return core.BuildTestID(file, parts)
}

// splitSuiteName splits a testify suite t.Name() into title parts.
// "TestAuthSuite/TestLogin" → ["AuthSuite", "TestLogin"]
// The outer "TestXxx" wrapper generated by suite.Run is stripped.
func splitSuiteName(name string) []string {
	parts := strings.SplitN(name, "/", 2)
	if len(parts) == 1 {
		return []string{stripTestPrefix(parts[0])}
	}
	// parts[0] is the Go test function name (e.g. "TestAuthSuite")
	// parts[1] is the suite method name (e.g. "TestLogin")
	return []string{stripTestPrefix(parts[0]), parts[1]}
}

// stripTestPrefix removes the "Test" prefix from a suite runner name so the
// test ID matches what users see in the suite struct name.
// "TestAuthSuite" → "AuthSuite"
func stripTestPrefix(s string) string {
	if strings.HasPrefix(s, "Test") {
		return s[4:]
	}
	return s
}

// callerTestFile walks the call stack and returns the path of the first
// _test.go file found. Called from SetupSuite where the user's TestXxx
// function is still in the goroutine's call stack.
func callerTestFile() string {
	for depth := 1; depth < 30; depth++ {
		_, file, _, ok := runtime.Caller(depth)
		if !ok {
			break
		}
		if strings.HasSuffix(file, "_test.go") {
			return file
		}
	}
	return "unknown"
}
