package testify

import (
	"runtime"
	"strings"

	"github.com/get-skipper/skipper-go/core"
)

// testIDFromSuite builds a Skipper test ID for a testify suite test.
//
// t.Name() inside a testify suite method returns "TestSuiteName/TestMethodName".
// We split on "/" and walk the call stack to find the actual test file,
// skipping testify and skipper internal frames.
func testIDFromSuite(name string) string {
	file := callerTestFile()
	parts := splitSuiteName(name)
	return core.BuildTestID(file, parts)
}

// splitSuiteName splits a testify suite t.Name() into title parts.
// "TestAuthSuite/TestLogin" → ["AuthSuite", "TestLogin"]
// The outer "TestXxx" wrapper generated by suite.Run is stripped.
func splitSuiteName(name string) []string {
	parts := strings.SplitN(name, "/", 2)
	if len(parts) == 1 {
		return []string{stripTestPrefix(parts[0])}
	}
	// parts[0] is the Go test function name (e.g. "TestAuthSuite")
	// parts[1] is the suite method name (e.g. "TestLogin")
	return []string{stripTestPrefix(parts[0]), parts[1]}
}

// stripTestPrefix removes the "Test" prefix from a suite runner name so the
// test ID matches what users see in the suite struct name.
// "TestAuthSuite" → "AuthSuite"
func stripTestPrefix(s string) string {
	if strings.HasPrefix(s, "Test") {
		return s[4:]
	}
	return s
}

// callerTestFile walks the call stack to find the first frame that belongs
// to user test code (not testify, not skipper, not the Go runtime).
func callerTestFile() string {
	for depth := 1; depth < 30; depth++ {
		_, file, _, ok := runtime.Caller(depth)
		if !ok {
			break
		}
		if isInternalFrame(file) {
			continue
		}
		return file
	}
	return "unknown"
}

func isInternalFrame(file string) bool {
	return strings.Contains(file, "testify/suite") ||
		strings.Contains(file, "stretchr/testify") ||
		strings.Contains(file, "skipper-go/testify") ||
		strings.Contains(file, "testing/testing.go") ||
		strings.Contains(file, "runtime/")
}
